#!/usr/bin/env php
<?php

require 'bootstrap/app.php';

if(isset($argv[1])){
    if($argv[1] == 'storage:link'){
        if(symlink( dirname(__FILE__) . '/storage/app/public',  dirname(__FILE__) . '/public/storage' )){
            echo 'Storage Symlink Created';
        }
    }
}

